/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiOgStaticRouteImport } from './routes/api/og-static'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as MainUsernameRouteImport } from './routes/_main/$username'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as MainUsernameIndexRouteImport } from './routes/_main/$username.index'
import { Route as ApiS3CoverImageRouteImport } from './routes/api/s3.cover-image'
import { Route as ApiOrpcSplatRouteImport } from './routes/api/orpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as MainThreadsNewRouteImport } from './routes/_main/threads.new'
import { Route as MainUsernameSettingsRouteImport } from './routes/_main/$username_.settings'
import { Route as MainUsernameSettingsIndexRouteImport } from './routes/_main/$username_.settings.index'
import { Route as MainUsernameThreadsThreadSlugRouteImport } from './routes/_main/$username_.threads.$threadSlug'
import { Route as MainUsernameSettingsAccountRouteImport } from './routes/_main/$username_.settings.account'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const ApiOgStaticRoute = ApiOgStaticRouteImport.update({
  id: '/api/og-static',
  path: '/api/og-static',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const MainUsernameRoute = MainUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MainRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const MainUsernameIndexRoute = MainUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainUsernameRoute,
} as any)
const ApiS3CoverImageRoute = ApiS3CoverImageRouteImport.update({
  id: '/api/s3/cover-image',
  path: '/api/s3/cover-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainThreadsNewRoute = MainThreadsNewRouteImport.update({
  id: '/threads/new',
  path: '/threads/new',
  getParentRoute: () => MainRoute,
} as any)
const MainUsernameSettingsRoute = MainUsernameSettingsRouteImport.update({
  id: '/$username_/settings',
  path: '/$username/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainUsernameSettingsIndexRoute =
  MainUsernameSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainUsernameSettingsRoute,
  } as any)
const MainUsernameThreadsThreadSlugRoute =
  MainUsernameThreadsThreadSlugRouteImport.update({
    id: '/$username_/threads/$threadSlug',
    path: '/$username/threads/$threadSlug',
    getParentRoute: () => MainRoute,
  } as any)
const MainUsernameSettingsAccountRoute =
  MainUsernameSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => MainUsernameSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$username': typeof MainUsernameRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/api/og-static': typeof ApiOgStaticRoute
  '/$username/settings': typeof MainUsernameSettingsRouteWithChildren
  '/threads/new': typeof MainThreadsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/s3/cover-image': typeof ApiS3CoverImageRoute
  '/$username/': typeof MainUsernameIndexRoute
  '/$username/settings/account': typeof MainUsernameSettingsAccountRoute
  '/$username/threads/$threadSlug': typeof MainUsernameThreadsThreadSlugRoute
  '/$username/settings/': typeof MainUsernameSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/og': typeof ApiOgRoute
  '/api/og-static': typeof ApiOgStaticRoute
  '/threads/new': typeof MainThreadsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/s3/cover-image': typeof ApiS3CoverImageRoute
  '/$username': typeof MainUsernameIndexRoute
  '/$username/settings/account': typeof MainUsernameSettingsAccountRoute
  '/$username/threads/$threadSlug': typeof MainUsernameThreadsThreadSlugRoute
  '/$username/settings': typeof MainUsernameSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_main/$username': typeof MainUsernameRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/api/og-static': typeof ApiOgStaticRoute
  '/_main/': typeof MainIndexRoute
  '/_main/$username_/settings': typeof MainUsernameSettingsRouteWithChildren
  '/_main/threads/new': typeof MainThreadsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/s3/cover-image': typeof ApiS3CoverImageRoute
  '/_main/$username/': typeof MainUsernameIndexRoute
  '/_main/$username_/settings/account': typeof MainUsernameSettingsAccountRoute
  '/_main/$username_/threads/$threadSlug': typeof MainUsernameThreadsThreadSlugRoute
  '/_main/$username_/settings/': typeof MainUsernameSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/$username'
    | '/api/og'
    | '/api/og-static'
    | '/$username/settings'
    | '/threads/new'
    | '/api/auth/$'
    | '/api/orpc/$'
    | '/api/s3/cover-image'
    | '/$username/'
    | '/$username/settings/account'
    | '/$username/threads/$threadSlug'
    | '/$username/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/og'
    | '/api/og-static'
    | '/threads/new'
    | '/api/auth/$'
    | '/api/orpc/$'
    | '/api/s3/cover-image'
    | '/$username'
    | '/$username/settings/account'
    | '/$username/threads/$threadSlug'
    | '/$username/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_main/$username'
    | '/api/og'
    | '/api/og-static'
    | '/_main/'
    | '/_main/$username_/settings'
    | '/_main/threads/new'
    | '/api/auth/$'
    | '/api/orpc/$'
    | '/api/s3/cover-image'
    | '/_main/$username/'
    | '/_main/$username_/settings/account'
    | '/_main/$username_/threads/$threadSlug'
    | '/_main/$username_/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
  ApiOgStaticRoute: typeof ApiOgStaticRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
  ApiS3CoverImageRoute: typeof ApiS3CoverImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/og-static': {
      id: '/api/og-static'
      path: '/api/og-static'
      fullPath: '/api/og-static'
      preLoaderRoute: typeof ApiOgStaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/$username': {
      id: '/_main/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof MainUsernameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/$username/': {
      id: '/_main/$username/'
      path: '/'
      fullPath: '/$username/'
      preLoaderRoute: typeof MainUsernameIndexRouteImport
      parentRoute: typeof MainUsernameRoute
    }
    '/api/s3/cover-image': {
      id: '/api/s3/cover-image'
      path: '/api/s3/cover-image'
      fullPath: '/api/s3/cover-image'
      preLoaderRoute: typeof ApiS3CoverImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/threads/new': {
      id: '/_main/threads/new'
      path: '/threads/new'
      fullPath: '/threads/new'
      preLoaderRoute: typeof MainThreadsNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username_/settings': {
      id: '/_main/$username_/settings'
      path: '/$username/settings'
      fullPath: '/$username/settings'
      preLoaderRoute: typeof MainUsernameSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username_/settings/': {
      id: '/_main/$username_/settings/'
      path: '/'
      fullPath: '/$username/settings/'
      preLoaderRoute: typeof MainUsernameSettingsIndexRouteImport
      parentRoute: typeof MainUsernameSettingsRoute
    }
    '/_main/$username_/threads/$threadSlug': {
      id: '/_main/$username_/threads/$threadSlug'
      path: '/$username/threads/$threadSlug'
      fullPath: '/$username/threads/$threadSlug'
      preLoaderRoute: typeof MainUsernameThreadsThreadSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username_/settings/account': {
      id: '/_main/$username_/settings/account'
      path: '/account'
      fullPath: '/$username/settings/account'
      preLoaderRoute: typeof MainUsernameSettingsAccountRouteImport
      parentRoute: typeof MainUsernameSettingsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainUsernameRouteChildren {
  MainUsernameIndexRoute: typeof MainUsernameIndexRoute
}

const MainUsernameRouteChildren: MainUsernameRouteChildren = {
  MainUsernameIndexRoute: MainUsernameIndexRoute,
}

const MainUsernameRouteWithChildren = MainUsernameRoute._addFileChildren(
  MainUsernameRouteChildren,
)

interface MainUsernameSettingsRouteChildren {
  MainUsernameSettingsAccountRoute: typeof MainUsernameSettingsAccountRoute
  MainUsernameSettingsIndexRoute: typeof MainUsernameSettingsIndexRoute
}

const MainUsernameSettingsRouteChildren: MainUsernameSettingsRouteChildren = {
  MainUsernameSettingsAccountRoute: MainUsernameSettingsAccountRoute,
  MainUsernameSettingsIndexRoute: MainUsernameSettingsIndexRoute,
}

const MainUsernameSettingsRouteWithChildren =
  MainUsernameSettingsRoute._addFileChildren(MainUsernameSettingsRouteChildren)

interface MainRouteChildren {
  MainUsernameRoute: typeof MainUsernameRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
  MainUsernameSettingsRoute: typeof MainUsernameSettingsRouteWithChildren
  MainThreadsNewRoute: typeof MainThreadsNewRoute
  MainUsernameThreadsThreadSlugRoute: typeof MainUsernameThreadsThreadSlugRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainUsernameRoute: MainUsernameRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
  MainUsernameSettingsRoute: MainUsernameSettingsRouteWithChildren,
  MainThreadsNewRoute: MainThreadsNewRoute,
  MainUsernameThreadsThreadSlugRoute: MainUsernameThreadsThreadSlugRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
  ApiOgStaticRoute: ApiOgStaticRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
  ApiS3CoverImageRoute: ApiS3CoverImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
